### ISSUE TITLE
Another invalid credentials error

### ISSUE THREAD

**Issue by joaoborras** [BroadSoft-Xtended/Project-Chrome-Extension#11]
Good morning. I am trying to log into the dialer with my credentials but get the "invalid credentials" error.
I created a device with the (Business Communicator - UConePC) profile for one of my BW test users. 
The URL I get from this devide is http://xspclust.pbxl.net:80/dms/bc/pcUCone/config.xml and that is the one I am using. Then, I enter the user name and password but get the error message.
I also deleted the cache and restarted the browser several times with no success.
Could you, please, help me with this issue?

Thank you,
Joao Paulo

**Comment by broadsoftxtended** [comment]
Hi.

Please verify the URL you have entered on the sign in box. It must be prefixed by the protocol (http://) and point to an xsp that has xsi-actions deployed on it on the 'com.broadsoft.xsi-actions' context.

For instance, if  your xsp  hostname was xsp.test.com, then your url should be "http://xsp.test.com". Then enter a valid userid and password combination.

If you continue to get this error, please attach your logs, You can view them from Chrome->Tools->Extensions, then under the BroadSoft Xtended Dialer click on the link to 'background.html'. This will show the logs of the sign-in.

**Comment by joaoborras** [comment]
Hi! Well, I tried to sign in again but got same errors.
I used 2 URL`s. Here is the simplified one: http://xspclust.pbxl.net
The other one I got from BW group configuration and is this one: http://xspclust.pbxl.net:80/dms/bc/pcUCone/config.xml
This last URL I got when adding a UConePC agent to my BW user.

About the logs, I am not user how to get it because when I click the background.html file, it actually opens a window with several tabs. Here is the 1st tab:
![image](https://f.cloud.github.com/assets/6582140/2095573/e57f8d96-8ee9-11e3-95f0-3627f930d553.png)

Here is the image from the Resources tab:
![image](https://f.cloud.github.com/assets/6582140/2095577/003009d6-8eea-11e3-9bba-e67bcb9982cd.png)

And here is the Console tab:
![image](https://f.cloud.github.com/assets/6582140/2095584/399e66c2-8eea-11e3-9ea1-b5c15fa241f5.png)

I appreciate if you can help me further on this issue.

Thanks a lot,
Joao Paulo

**Comment by broadsoftxtended** [comment]
You should user the first url "http://xspclust.pbxl.net" when signing in.
Can you verify that you are using the correct right userid/password? There is an xsi-actions test page where you can directly try to get the user profile just using xsi-actions. The URL is here.

http://xsp2.pbxl.net/com.broadsoft.xsi-actions/test/v2.0/user/userid/profile_Get.html

Just enter the userid for the user you are testing in the userid box and click "Get".  It will prompt you for the userid/password credentials. If that doesn't work, then you have a problem with your xsi-actions setup.

**Comment by joaoborras** [comment]
It worked now but with a different URL.
I used the URS for test that you gave me, and got this page:
![image](https://f.cloud.github.com/assets/6582140/2105929/45f41882-8f98-11e3-9b95-45a0c5653908.png)

As you can see, the host is different(xsp2.pbxl.net). So, I used http://xsp2.pbxl.net instead(our network is clustered and the real URL`s are xsp1.pbxl.net and xsp2.pbxl.net and xsp.pbxl.net is the cluster URL) and I could register now.

I have 2 questions yet:
1. where do you get the test URL? I ask that because I will start to develop with xsi and would be useful to have this kind of information.
2. after I logged in the BW extension, I got a new page with a message to restart the browser before continue. Here is the screen shot:
![image](https://f.cloud.github.com/assets/6582140/2105955/dfec7f92-8f98-11e3-8305-26855d33d865.png)

Then I closed the browser but this crashed my computer and caused it to restart. Any reason for that? I am using Windows XP.

So, thanks a lot for your prompt and kind support! Best regards,
Joao Paulo

**Comment by broadsoftxtended** [comment]
Great.
1. When we entered the cluster fqdn (http://xspclust.pbxl.net/com.broadsoft.xsi-actions/test/) the browser resolved it to http://xsp2.pbxl.net/com.broadsoft.xsi-actions/test/ . Perhaps you have a DNS issue?
2. Not sure why your computer would have crashed after the restart, and it should not be related to the xtension.  The reason the restart is required it to make sure that credentials cached by the browser are cleared for the next login.

**Comment by joaoborras** [comment]
I will have a check on our DNS.
About the crash, it crashed again when I closed Chrome in the end of the day. I will keep an eye on it to see if it relates to the extension. Actually, I have another one working at the same time so, it can be that one instead.

Thank you for your prompt and good help!
