### ISSUE TITLE
Unable to login to Engin Broadworks (Australia)

### ISSUE THREAD

**Issue by marine44** [BroadSoft-Xtended/Project-Chrome-Extension#17]
I am unsure what to use for the broadworks server address. To login to broad works I go to https://voicemanager.engin.com.au

Is this the address I use?

Also what is the format of the username?

**Comment by NathanDalley** [comment]
It wasn't simple for us either, I packet sniffed an application our provider gave us to find out API server.
I tried a few things at random and found yours server: https://xsi.engin.com.au
Its not obvious unless you've dug through the Broadsofts forums ;)

The username will likely be your broadworks login.  
For us it is <phnumber>@<domain.com.au> (@engin.com.au perhaps?)

**Comment by marine44** [comment]
Thanks for the really fast reply!!! I've tried https://xsi.engin.com.au with the username and password for the extension that I use to login to Broadworks - but no dice... all I get is "Invalid credentials. Please verify the information is correct and try again."

I was so excited about this!!!

**Comment by NathanDalley** [comment]
My bad, Try: http://xsi.engin.com.au
What I found was: http://xsi.engin.com.au/com.broadsoft.xsi-actions/test/
I changed the url to https without actually testing it!

**Comment by marine44** [comment]
Boom! I am logged in now! Thanks a lot!!!

When I click phone numbers though chrome opens "hangouts" to call them! Woops! Any ideas?

**Comment by NathanDalley** [comment]
No idea, I see the click to dial feature checked, but I haven't yet found something clickable that works!
