### ISSUE TITLE
Can´t dial directly

### ISSUE THREAD

**Issue by gmasrih** [BroadSoft-Xtended/Project-Chrome-Extension#5]
Hi, I can outdial only by double clicking the call logs, but Im not able to do it typing a number in the bar or by searching contacts and double clicking them.
Can you help me out?

Thx

**Comment by broadsoftxtended** [comment]
When you start typing in the Search and Dial text box, do you see search results? Are you typing in numbers or extension?

Is there a way for you to access the xsi-actions logs on the XSP? You can look at the logs to see if the out-dial request is making it to the XSP or not.

**Comment by broadsoftxtended** [comment]
Closing. No response received from last update.
