### ISSUE TITLE
Crash when try to Configure

### ISSUE THREAD

**Issue by jteranmcm** [BroadSoft-Xtended/Project-Chrome-Extension#6]
When I install the Dialer and then select the option Config, the Dialer open a lot of Tabs in the Google Chrome making this crush.

**Comment by broadsoftxtended** [comment]
What OS and version are you on? What version of chrome? Are the tabs blank? They should display the Google OAuth page asking you to grant access to your Google Contacts.

**Comment by broadsoftxtended** [comment]
Can you try the following steps:
1. Log out of ALL your Google Accounts
2. Remove the extension
3. Clear your cache
4. Add the extension

**Comment by jteranmcm** [comment]
Thanks for your fast answer

Windows 7 Professional 64 bits,
Chrome 30.0.1599101 m
You can see blank as faster as appear the next one TAB, has the URL has chrome-extension://hdcafonebnjhgmdigdapaaloiapofdln/chrome:ex_oauth.html
Jesus

**Comment by broadsoftxtended** [comment]
can you try logging out of google and clearing your cache?

**Comment by broadsoftxtended** [comment]
We are going to release a new version soon that uses OAuth 2.0. That should alleviate this issue.

**Comment by jteranmcm** [comment]
OK Thank you.

**Comment by broadsoftxtended** [comment]
Closing. New version using OAuth 2.0 has been released which resolves this issue.
