### ISSUE TITLE
Invalid Credentials

### ISSUE THREAD

**Issue by pjmdaddy** [BroadSoft-Xtended/Project-Chrome-Extension#7]
I am trying to log into my Broadsoft Chrome extender and I am getting invalid credentials.  I have posed this to Broadsoft but they can log in on their PC using my credentials.  
What could be the issue here?
Using Chrome Ver - 31.0.1650.57 m

Thanks

**Comment by broadsoftxtended** [comment]
Can you clear your browser cache and try again?

**Comment by pjmdaddy** [comment]
Cleared all of my Chrome's browser cache and still get the invalid credentials error.
Thanks for replying on such short notice.

**Comment by broadsoftxtended** [comment]
If BroadSoft can login using your credentials, then your creds should be good.

Can you verify your URL? Is there a typo there?  If it looks good, then try
the following:
1) Remove the extension
2) Restart your browser
3) Install the extension and try to login again

**Comment by pjmdaddy** [comment]
Steps 1-3 have been completed, still unable to log in.  Let me know via email if you want to try logging in from where you are.
patrick.morris@ibbs.com

**Comment by broadsoftxtended** [comment]
Closing, Upon further investigation, the url was missing the "http://"  portocol prefix and is resolved now.
