### ISSUE TITLE
Outdial Stripping "+"

### ISSUE THREAD

**Issue by BenGatewood** [BroadSoft-Xtended/Project-Chrome-Extension#8]
Hey All,

It appears to me that the leading "+" of an E.164 formatted directory entry is being stripped somewhere in the browser-end before the out dial command gets to the XSP.

Possible?

**Comment by broadsoftxtended** [comment]
Yes, there are a few places where the "number" is modified before calling the XSI-Actions Dial command:
background.js:28
background.js:94
dotabs.js:94

**Comment by BenGatewood** [comment]
Gotcha - thanks. I'll check those out.

**Comment by moreiraeduardo** [comment]
Where can I check those ?
I cannot find the way it works.

**Comment by broadsoftxtended** [comment]
closing. Question answered in previous post.
